In [1]:
import torch

In [2]:
randint = torch.randint(-100,100,(6,))
randint

tensor([-100,   -1,   97,  -19,   97,   53])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.3, 3.4], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.3000, 3.4000],
        [4.9000, 5.2000]])

In [2]:
zeroes = torch.zeros(2, 3)
print(zeroes)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
import torch
print("working")

working


In [4]:
ones = torch.ones(3, 4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [5]:
input = torch.empty(2, 3)
input

tensor([[ 4.1353e-28,  4.5741e-41, -1.1247e-33],
        [ 3.0862e-41,  4.4842e-44,  0.0000e+00]])

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [10]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[ 94594738041760,  94594737886192,           65536],
        [140195147711489,              48,              48]])