In [1]:
import torch

In [2]:
randint = torch.randint(-100,100,(6,))
randint

tensor([-100,   -1,   97,  -19,   97,   53])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.3, 3.4], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.3000, 3.4000],
        [4.9000, 5.2000]])

In [2]:
zeroes = torch.zeros(2, 3)
print(zeroes)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
import torch
print("working")

working


In [4]:
ones = torch.ones(3, 4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [5]:
input = torch.empty(2, 3)
input

tensor([[ 4.1353e-28,  4.5741e-41, -1.1247e-33],
        [ 3.0862e-41,  4.4842e-44,  0.0000e+00]])

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [10]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[ 94594738041760,  94594737886192,           65536],
        [140195147711489,              48,              48]])

In [2]:
int_64 = torch.randint(1, (3, 2))
# type int64

float_32 = torch.rand(2, 3)
# type float32

result = torch.matmul(int_64, float_32)
print(result)

RuntimeError: expected m1 and m2 to have the same dtype, but got: long int != float

In [3]:
int_64 = int_64.to(torch.float32)

result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# Dot product: multiply corresponding values and add the products

a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

manual_dot_product = (1*4) + (2*5) + (3*6)
pytorch_dot_product = torch.dot(a, b)

print("Manual:", manual_dot_product)
print("PyTorch:", pytorch_dot_product)

Manual: 32
PyTorch: tensor(32.)


In [5]:
# Matrix multiplication shape rule:
# (m x n) @ (n x p) -> (m x p)

A = torch.tensor([[1., 2.],
                  [3., 4.],
                  [5., 6.]])

B = torch.tensor([[7., 8., 9.],
                  [10., 11., 12.]])

print("A shape:", A.shape)
print("B shape:", B.shape)

C = A @ B

print("Result shape:", C.shape)
print(C)

A shape: torch.Size([3, 2])
B shape: torch.Size([2, 3])
Result shape: torch.Size([3, 3])
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [6]:
# Matrix multiplication also requires compatible dtypes.

int_tensor = torch.tensor([[1, 2],
                           [3, 4]])

float_tensor = torch.tensor([[1., 2.],
                             [3., 4.]])

print(int_tensor.dtype)
print(float_tensor.dtype)

# Convert the integer tensor before matrix multiplication
int_tensor = int_tensor.to(torch.float32)

result = int_tensor @ float_tensor

print(result)

torch.int64
torch.float32
tensor([[ 7., 10.],
        [15., 22.]])


In [ ]:
x = torch.tensor([10], dtype=torch.float32)
y = F.tanh(x)
print(y)