In [1]:
import torch
import numpy as np
import time

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [2]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])

# Each probability corresponds to its index:
# index 0 has probability 0.1
# index 1 has probability 0.9

# Draw 10 samples according to these probabilities
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)

print(samples)

tensor([1, 1, 1, 1, 0, 1, 1, 1, 1, 1])


In [3]:
# torch.multinomial samples indices according to their probabilities.
# Here index 0 has a 10% chance and index 1 has a 90% chance.
# replacement=True allows the same index to be selected multiple times.

In [7]:
tensor = torch.tensor([1, 2, 3, 4]) # joining tensors
out = torch.cat((tensor, torch.tensor([5])), dim=0)

out

tensor([1, 2, 3, 4, 5])

In [6]:
# torch.cat() joins tensors together along an existing dimension. Deosnt create a new dimension
# Here [5] is added to the end of the original 1D tensor.

In [8]:
out = torch.tril(torch.ones(5, 5)) # lower triangular matrix
out
# torch.tril() keeps the lower triangular part of a matrix.
# Values above the main diagonal are replaced with 0.
# tril - triangular lower

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [9]:
# replacing selected values
out = torch.tril(torch.ones(5, 5)) == 0 # which values in the triangluar matrix are equal to zero that creates a boolean tensor of true and false
out = out.masked_fill(out, float('-inf')) # replaces the selected positions with -inf or negative infinity

out
# Creates a mask for positions above the diagonal.
# masked_fill() replaces the True positions with negative infinity.
# This is useful for preventing attention to future tokens.
# masked theory -> minus infinity

tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

In [10]:
torch.exp(out)
# torch.exp() calculates e^x for every element in the tensor.
# e^(-infinity) becomes 0, which is useful when applying attention masks.

tensor([[1.0000, 2.7183, 2.7183, 2.7183, 2.7183],
        [1.0000, 1.0000, 2.7183, 2.7183, 2.7183],
        [1.0000, 1.0000, 1.0000, 2.7183, 2.7183],
        [1.0000, 1.0000, 1.0000, 1.0000, 2.7183],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])

In [11]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)

out.shape
# transpose() swaps two dimensions of a tensor.
# Here dimensions 0 and 2 exchange positions.

torch.Size([4, 3, 2])

In [12]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor
# torch.stack() combines tensors by creating a NEW dimension.
# Unlike torch.cat(), it does not simply join an existing dimension.

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
# torch.cat()     joins along an EXISTING dimension
# torch.stack()   creates a NEW dimension

In [15]:
import torch.nn as nn

sample = torch.tensor([10., 10., 10.])

linear = nn.Linear(3, 3, bias=False)# bias=False means this layer only applies the learned weight matrix,
# without adding a separate learned bias vector.

print(linear(sample))

# nn.Linear creates a fully connected linear layer.
# It transforms an input using learned weights.
# bias=False means no additional bias term is added.

tensor([-8.9081, -9.2839,  2.7383], grad_fn=<SqueezeBackward4>)


In [16]:
#Training changes these weights so that the network learns useful transformations of its inputs.


In [ ]:
import torch.nn.functional as F

tensor = torch.tensor([1.0, 2.0, 3.0])

softmax_output = F.softmax(tensor, dim=0)

print(softmax_output)

